services:
  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authservice-api
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SqlServer: Server=sqlserver,1433;Database=AuthServiceDb;User Id=sa;Password=Your_strong_Password123;TrustServerCertificate=True;
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__User: guest
      RabbitMQ__Password: guest
      JwtSettings__Issuer: AuthService
      JwtSettings__Audience: AuthServiceClients
      JwtSettings__SecretKey: SuperSecretKeyForJwt1234567890

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: authservice-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_strong_Password123"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$${SA_PASSWORD}\" -C -Q \"SELECT 1\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s
    volumes:
      - sqlserver-data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: authservice-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  sqlserver-data:
